Add threshold above which the battery will be hidden
hastinbe/i3blocks-battery-plus pull request #8
Opened 2022-07-14 18:45 UTC by pathetic-lynx

My battery is barely ever fully charged so I added a threshold above which it is considered full if its not actively charging.

Could not get the commandline args to work, maybe you can take a look :)

2022-07-14 20:33 UTC, pathetic-lynx commented
Forgot to update README and example conf, I'll do that tomorrow

2022-07-15 14:19 UTC, hastinbe commented on battery-plus
> +        if $_HIDE_IF_CHARGED && [ $battery_percentage -ge $_HIDE_OVER_PERCENTAGE ]; then
Maybe _HIDE_OVER_PERCENTAGE should default to 100, otherwise anyone using -H is automatically opted-in to hide output if it's 85%

2022-07-15 14:20 UTC, hastinbe requested changes
_HIDE_OVER_PERCENTAGE should default to 100

2022-07-16 09:58 UTC, pathetic-lynx commented
Fair point. Any idea why the command line args are not working?

2022-07-16 13:31 UTC, merged

2022-07-16 13:39 UTC, hastinbe commented
> 

Yep, fixed in 65b8a59ade5b580429f8bbee943b5aac1b13c65c